sudo: false
dist: trusty
language: php

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
          sudo: required
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/phpunit/phpunit/phpunit

cache:
  directories:
    - $HOME/.composer/cache
